export const copyCatalog = {
  brandName: "Frame24",

  headerMyTickets: "Meus ingressos",
  headerEnter: "Entrar",
  headerAccount: "Conta",
  headerNowShowingToday: "Em cartaz hoje",

  searchGroupMovies: "Filmes",
  searchGroupCinemas: "Cinemas",
  searchGroupCities: "Cidades",
  searchOpenAria: "Abrir busca",
  searchDesktopPlaceholderPrefix: "Buscar filme ou cinema em",
  searchMobileTitle: "Buscar filme ou cinema",
  searchMobileDescription: "Procure filmes, cinemas e cidades sem trocar de tela.",
  searchMobilePlaceholderPrefix: "Buscar em",
  searchClose: "Fechar busca",
  searchQuickToday: "Hoje",
  searchQuickImax: "IMAX",
  searchQuickPromotions: "Promoções",
  searchQuickNearby: "Perto de você",
  searchPageEyebrow: "Busca",
  searchPageTitle: "Busque filme, cinema ou cidade",
  searchPageDescription: "Veja resultados completos para comparar horários e cinemas.",

  authTitle: "Entre para ver seus ingressos e pedidos",
  authDescription: "Acesse sua conta para acompanhar compras em qualquer dispositivo.",
  authBenefitOrders: "Acompanhe seu histórico de pedidos",
  authBenefitFastRecovery: "Recupere uma compra em segundos",
  authBenefitFastCheckout: "Finalize a compra no mesmo fluxo",
  authPanelTitleLogin: "Acessar conta",
  authPanelTitleRegister: "Criar conta",
  authPanelDescription: "Entre para continuar com seus ingressos e pedidos.",
  authTabLogin: "Entrar",
  authTabRegister: "Criar conta",
  authContinueWith: "Continuar com",
  authOrEmailPassword: "ou e-mail e senha",
  authEmailLabel: "E-mail",
  authPasswordLabel: "Senha",
  authNameLabel: "Nome completo",
  authEmailPlaceholder: "voce@email.com",
  authPasswordPlaceholder: "Sua senha",
  authPasswordHint: "No mínimo 8 caracteres",
  authNamePlaceholder: "Seu nome",
  authProviderGoogle: "Entrar com Google",
  authProviderApple: "Entrar com Apple",
  authProviderFacebook: "Entrar com Facebook",
  authErrorSignIn: "Não foi possível entrar.",
  authErrorSignInRetry: "Não foi possível entrar agora. Tente novamente.",
  authErrorSignUp: "Não foi possível criar a conta.",
  authErrorSignUpRetry: "Não foi possível criar a conta agora. Tente novamente.",

  homeBlockbusterEyebrow: "Destaque",
  homeBlockbusterTitle: "Filmes em destaque hoje",
  homeBlockbusterDescription: "Veja os títulos com mais procura e estreia próxima.",
  homeQuickEyebrow: "Atalhos rápidos",
  homeQuickTitle: "Vá direto ao que importa",
  homeQuickDescription: "Acesse sessões de hoje, em cartaz, pré-estreias e cinemas.",
  homeSessionsEyebrow: "Sessões de hoje",
  homeSessionsTitle: "Veja horários de hoje",
  homeNowPlayingTitle: "Escolha seu filme",
  homeNowPlayingCtaAllMovies: "Ver todos os filmes",
  homeComingSoonTitle: "Pré-estreias em destaque",
  homeTrustRefundTitle: "Troca e reembolso",
  homeTrustRefundDescription: "Veja as regras de cancelamento e remarcação antes de pagar.",
  homeTrustDigitalTitle: "Ingresso digital",
  homeTrustDigitalDescription: "Use o QR Code direto no celular para entrar na sessão.",
  homeTrustSupportTitle: "Suporte",
  homeTrustSupportDescription: "Ajuda para pagamento, sessão e acesso ao ingresso.",
  homeTrustWalletTitle: "Carteira digital",
  homeTrustWalletDescription: "Adicione seu ingresso na Apple Wallet ou Google Wallet.",
  homeCinemasEyebrow: "Cinemas próximos",
  homeCinemasTitle: "Escolha por bairro, rede e formato",
  homeCinemasDescription: "Compare opções da sua cidade e decida mais rápido.",
  cityPageEyebrow: "Cidade ativa",
  cityPageTitlePrefix: "O que assistir em",
  cityPageTitleSuffix: "hoje",
  cityPageDescription: "Encontre sessões por cinema, formato e horário.",
  cityPageQuickNavEyebrow: "Navegação rápida",
  cityPageQuickNavSearch: "Use a busca para trocar de filme ou cinema mantendo a cidade selecionada.",
  cityPageQuickNavToday: "Se a decisão é para hoje, comece por sessões.",
  cityPageQuickNavComingSoon: "Use Em breve para acompanhar estreias e pré-vendas.",
  cityPageSessionsTitle: "Horários e cinemas disponíveis agora",
  cityPageSessionsDescription: "Ideal para decidir pela melhor sessão disponível.",
  cityPageMoviesTitle: "Escolha seu filme",
  cityPageComingSoonTitle: "Pré-estreias em destaque",
  cityPageCinemasEyebrow: "Cinemas",
  cityPageCinemasTitle: "Escolha por rede ou bairro",
  cityPageCinemasDescription: "Veja os cinemas da cidade antes de decidir a sessão.",
  catalogEyebrow: "Catálogo",
  catalogTitlePrefix: "Filmes em",
  catalogDescription: "Filtre por gênero, formato e status com leitura rápida.",
  movieBrowserSearchPlaceholder: "Busque por filme, gênero ou formato",
  movieBrowserStatusLegend: "Status",
  movieBrowserStatusAll: "Todos",
  movieBrowserStatusNowShowing: "Em cartaz",
  movieBrowserStatusComingSoon: "Em breve",
  movieBrowserGenreLegend: "Gênero",
  movieBrowserFormatLegend: "Formato",
  movieBrowserLoadMore: "Carregar mais",

  heroCityLabelSeparator: ", ",
  heroEyebrow: "Filme em destaque",
  heroSupportingText: "Compare cinemas e formatos em um só lugar e compre sem complicação.",
  heroPrimaryCta: "Ver horários",
  heroSecondaryCta: "Assistir trailer",

  movieCardReleasePrefix: "Estreia",
  movieCardComingSoonBadge: "Pré-estreia",
  movieCardNextSessionPrefix: "Próxima sessão:",
  movieCardSessionsSuffix: "sessões disponíveis",
  movieCardPriceFromPrefix: "a partir de",
  movieCardPrimaryCta: "Ver horários",

  movieDetailSessionsEyebrow: "Sessões por cinema",
  movieDetailSessionsTitle: "Escolha horário, cinema e formato",
  movieDetailSessionsDescription: "Compare horários por cinema e vá direto para o assento.",
  movieDetailDateRailTitle: "Escolha o dia",
  movieDetailDuration: "Duração",
  movieDetailGenres: "Gêneros",
  movieDetailOriginalTitle: "Título original",
  movieDetailSessionsFoundSuffix: "sessões disponíveis agora",
  movieDetailCastLabel: "Elenco:",
  movieDetailFormatsLabel: "Formatos:",
  movieDetailAudioLabel: "Áudio:",
  movieDetailSubtitleLabel: "Legenda:",
  movieDetailTimesSuffix: "horários",
  movieDetailChooseSession: "Escolher sessão",
  movieDetailSwitchSession: "Trocar sessão",
  movieDetailChooseOnMap: "Selecione no mapa",
  movieDetailEmptyTitle: "As vendas para este filme ainda não começaram",
  movieDetailEmptyDescription: "Fique de olho! Os horários e sessões estarão disponíveis em breve.",
  movieDetailEmptyCinemaListTitle: "Cinemas onde o filme será exibido",
  movieDetailEmptyWeekTitle: "Próximos 7 dias",
  movieDetailEmptyFormatLabel: "Formatos confirmados:",
  movieDetailEmptyLanguageLabel: "Áudio/legenda:",
  movieDetailEmptyTimesLabel: "Horários mais comuns neste cinema:",
  movieDetailEmptyTimesFallback: "Horários em publicação",
  movieDetailEmptyStatusLabel: "Status:",
  movieDetailEmptyStatusValue: "Aguardando programação",
  movieDetailEmptyReleasePrefix: "Estreia prevista para",
  movieDetailEmptyReleaseFallback: "Data de estreia a confirmar",
  movieDetailEmptyCta: "Ver filmes em cartaz",
  movieDetailNoSessionsForDay: "Não há sessões para o dia selecionado. Tente outro dia acima.",

  checkoutSectionEyebrow: "Checkout",
  checkoutSectionTitle: "Revise seus dados e finalize o pagamento",
  checkoutSectionDescription: "Confirme assentos, dados e pagamento em uma única tela.",
  checkoutStepEyebrow: "Finalização",
  checkoutStepTitle: "Confirme seus dados",
  checkoutNameLabel: "Nome no ingresso",
  checkoutNamePlaceholder: "Como deve aparecer no ingresso",
  checkoutEmailLabel: "E-mail",
  checkoutEmailPlaceholder: "voce@exemplo.com",
  checkoutCpfLabel: "CPF para nota fiscal (quando exigido)",
  checkoutCpfPlaceholder: "000.000.000-00",
  checkoutSnacksEyebrow: "Snacks",
  checkoutSnacksTitle: "Retirada de snacks no balcão",
  checkoutPaymentEyebrow: "Pagamento",
  checkoutPaymentPix: "Pix",
  checkoutPaymentCard: "Cartão de crédito",
  checkoutPaymentWallet: "Apple Pay / Google Pay",
  checkoutCardDataTitle: "Dados do cartão",
  checkoutCardNumber: "Número do cartão",
  checkoutCardExpiry: "Validade",
  checkoutCardCvv: "CVV",
  checkoutCardHelp: "Em produção, os campos serão tokenizados com Stripe Payment Element.",
  checkoutPixTitle: "Pagamento por Pix",
  checkoutPixDescription: "Após confirmar, mostraremos QR Code e código copia e cola.",
  checkoutWalletTitle: "Carteira digital",
  checkoutWalletDescription: "Apple Pay e Google Pay aparecem em dispositivos compatíveis.",
  checkoutSummaryEyebrow: "Resumo do pedido",
  checkoutSummaryTitle: "Pedido",
  checkoutTicketsLabel: "Ingressos",
  checkoutTotalLabel: "Total",
  checkoutSubmit: "Confirmar compra",
  checkoutSubmitting: "Processando...",
  checkoutCardValidationHint: "Preencha os dados do cartão para liberar a confirmação.",
  checkoutClearSelection: "Limpar seleção",

  orderEyebrow: "Confirmação",
  orderDescription: "Seu ingresso está pronto para QR Code, carteira digital e envio por e-mail.",
  orderTotalPaid: "Total pago",
  orderRefundHint: "Consulte as regras de troca e reembolso na área de pedidos.",

  footerDescription: "Compre ingressos, compare horários e acesse seu histórico em um só lugar.",
  footerProfileLink: "Perfil",
  footerSearchLink: "Busca",
  footerExplorePrefix: "Explorar",

  stateErrorEyebrow: "Erro",
  stateErrorTitle: "Algo deu errado",
  stateErrorDescription: "Não foi possível carregar esta página agora. Tente novamente.",
  stateErrorRetry: "Tentar novamente",
  stateNotFoundEyebrow: "Página não encontrada",
  stateNotFoundTitle: "Não encontramos este conteúdo",
  stateNotFoundDescription: "Confira o link ou volte para escolher uma cidade e ver os horários.",
  stateNotFoundHome: "Voltar para a home",

  profileEyebrow: "Minha conta",
  profileOverviewTitlePrefix: "Olá, ",
  profileOverviewFallbackTitle: "Minha conta",
  profileOverviewDescription: "Acompanhe pedidos, ingressos, segurança e privacidade da sua conta.",
  profileOverviewLoading: "Carregando sua conta...",
  profileOverviewStatsOrders: "Pedidos",
  profileOverviewStatsTickets: "Ingressos",
  profileOverviewStatsTotalPaid: "Total pago",
  profileOverviewQuickActions: "Ações rápidas",
  profileOverviewActionOrders: "Ver pedidos",
  profileOverviewActionEditAccount: "Editar conta",
  profileOverviewActionSessions: "Sessões ativas",
  profileOverviewLinksTitle: "Contas vinculadas por cinema/rede",
  profileOverviewLinksEmpty: "Nenhuma conta vinculada encontrada.",
  profileOverviewTenantUnavailable: "Identificador indisponível",
  profileOverviewLevelFallback: "Sem nível",

  profileAuthTitle: "Entre para acessar sua conta",
  profileAuthDescription: "Veja pedidos, ingressos e configurações da sua conta.",
  profileAuthBackHome: "Voltar para a home",

  profileAccountTitle: "Conta e dados fiscais",
  profileAccountDescription: "Atualize seus dados pessoais, endereço fiscal e preferências.",
  profileAccountLoading: "Carregando dados da conta...",
  profileAccountEmailLabel: "E-mail da conta",
  profileAccountOpenEmailPage: "Abrir confirmação de e-mail",
  profileAccountPersonalTitle: "Dados pessoais",
  profileAccountPersonalDescription: "Mantenha seus dados atualizados para compras e suporte.",
  profileAccountSave: "Salvar dados",
  profileAccountSaving: "Salvando...",
  profileAccountUpdated: "Dados atualizados com sucesso.",
  profileAccountUpdateError: "Não foi possível atualizar os dados.",
  profileAccountPhonePlaceholder: "(71) 99999-0000",
  profileAccountBirthDate: "Data de nascimento",
  profileAccountCommunicationPreferences: "Preferências de comunicação",
  profileAccountAcceptEmail: "Receber avisos por e-mail",
  profileAccountAcceptSms: "Receber avisos por SMS",
  profileAccountAcceptMarketing: "Receber ofertas e novidades",
  profileAddressTitle: "Endereço fiscal",
  profileAddressDescription: "Usado para emissão de nota fiscal quando necessário.",
  profileAddressUpdated: "Endereço fiscal atualizado.",
  profileAddressUpdateError: "Não foi possível atualizar o endereço.",
  profileAddressSave: "Salvar endereço",
  profileAddressZipPlaceholder: "40000-000",
  profileAddressStreetPlaceholder: "Rua, avenida, número e complemento",
  profileAddressCityPlaceholder: "Salvador",
  profileAddressStatePlaceholder: "BA",

  profileEmailDialogTrigger: "Alterar e-mail",
  profileEmailDialogTitle: "Trocar e-mail da conta",
  profileEmailDialogDescription: "Peça a troca e confirme com o código enviado ao novo e-mail.",
  profileEmailDialogStepRequest: "1. Solicitar troca",
  profileEmailDialogStepConfirm: "2. Confirmar código",
  profileEmailDialogCurrentEmail: "E-mail atual",
  profileEmailDialogNewEmail: "Novo e-mail",
  profileEmailDialogNewEmailPlaceholder: "novo@email.com",
  profileEmailDialogRequestId: "ID da solicitação",
  profileEmailDialogToken: "Código de confirmação",
  profileEmailDialogRequestPlaceholder: "req_...",
  profileEmailDialogTokenPlaceholder: "Cole o código enviado por e-mail",
  profileEmailDialogSendConfirm: "Enviar confirmação",
  profileEmailDialogConfirm: "Confirmar troca",
  profileEmailDialogSending: "Enviando...",
  profileEmailDialogConfirming: "Confirmando...",
  profileEmailDialogRequested: "Enviamos a confirmação para o novo e-mail.",
  profileEmailDialogRequestError: "Não foi possível solicitar a troca de e-mail.",
  profileEmailDialogConfirmed: "E-mail atualizado com sucesso.",
  profileEmailDialogConfirmError: "Não foi possível confirmar a troca.",
  profileEmailPageTitle: "Confirmar novo e-mail",
  profileEmailPageDescription: "Conclua a alteração do seu e-mail.",
  profileEmailPageLoading: "Carregando...",
  profileEmailPageHelp: "Preencha o ID da solicitação e o código enviados para o novo e-mail.",
  profileEmailPageUpdated: "E-mail confirmado e atualizado com sucesso.",
  profileEmailPageError: "Falha ao confirmar troca de e-mail.",

  profileOrdersTitle: "Pedidos e histórico",
  profileOrdersDescription: "Veja itens do pedido, status e solicitações de reembolso.",
  profileOrdersLoading: "Carregando pedidos...",
  profileOrdersFilters: "Filtros",
  profileOrdersFilterAll: "Todos",
  profileOrdersFilterActive: "Ativos",
  profileOrdersFilterRefundable: "Reembolsáveis",
  profileOrdersCardTitle: "Pedidos",
  profileOrdersEmpty: "Você ainda não tem pedidos.",
  profileOrdersRefundAvailable: "Reembolso por item disponível",
  profileOrdersDetails: "Detalhes",

  profileOrderDetailsTitle: "Detalhes do pedido",
  profileOrderDetailsDescription: "Confira itens, status e ações disponíveis.",
  profileOrderDetailsLoading: "Carregando pedido...",
  profileOrderDetailsNotFound: "Pedido não encontrado.",
  profileOrderDetailsBackToOrders: "Voltar para pedidos",
  profileOrderDetailsPaymentMethod: "Forma de pagamento:",
  profileOrderDetailsTicketType: "Ingresso",
  profileOrderDetailsConcessionType: "Bomboniere",
  profileOrderDetailsOpenTicket: "Abrir ingresso",
  profileOrderDetailsNoStatus: "Sem status",
  profileOrderDetailsRefundRequests: "Solicitações de reembolso",
  profileOrderDetailsRefundEmpty: "Nenhuma solicitação vinculada a este pedido.",
  profileOrderDetailsRefundTitle: "Solicitar reembolso",
  profileOrderDetailsRefundSubtitle: "Selecione itens elegíveis para análise.",
  profileOrderDetailsRefundNoItems: "Não há itens elegíveis para reembolso neste pedido.",
  profileOrderDetailsRefundReason: "Motivo (opcional)",
  profileOrderDetailsRefundReasonPlaceholder: "Conte rapidamente o motivo do pedido",
  profileOrderDetailsRefundTrigger: "Solicitar reembolso por item",
  profileOrderDetailsRefundSubmit: "Enviar solicitação",
  profileOrderDetailsRefundSubmitting: "Enviando...",
  profileOrderDetailsRefundClose: "Fechar",
  profileOrderDetailsRefundSelectOne: "Selecione ao menos um item.",
  profileOrderDetailsRefundCreated: "Solicitação criada com sucesso.",
  profileOrderDetailsRefundError: "Não foi possível criar a solicitação.",

  profileTicketsTitle: "Meus ingressos",
  profileTicketsDescription: "Acesse QR Code, PDF e reenvio por e-mail.",
  profileTicketsLoading: "Carregando ingressos...",
  profileTicketsEmpty: "Nenhum ingresso encontrado.",
  profileTicketsOpen: "Abrir",
  profileTicketTitle: "Ingresso digital",
  profileTicketDescription: "Acesse QR Code, PDF e reenvio por e-mail.",
  profileTicketLoading: "Carregando ingresso...",
  profileTicketNotFound: "Ingresso não encontrado.",
  profileTicketBackToOrder: "Voltar para pedido",
  profileTicketBackToOrders: "Voltar para pedidos",
  profileTicketHeader: "Ingresso digital",
  profileTicketNumberPrefix: "Ingresso #",
  profileTicketSeat: "Assento:",
  profileTicketValue: "Valor:",
  profileTicketStatus: "Status:",
  profileTicketStatusUsed: "Utilizado",
  profileTicketStatusActive: "Ativo",
  profileTicketDownloadPdf: "Baixar PDF",
  profileTicketResendEmail: "Reenviar por e-mail",
  profileTicketResendingEmail: "Enviando...",
  profileTicketViewInOrder: "Ver ingresso no pedido",
  profileTicketResendError: "Não foi possível reenviar o e-mail.",
  profileTicketResendSuccess: "Ingresso reenviado para o e-mail cadastrado.",

  profileSecurityTitle: "Segurança da conta",
  profileSecurityDescription: "Gerencie sessões e dispositivos ativos.",
  profileSecurityLoading: "Carregando segurança...",
  profileSecurityPanelTitle: "Sessões e dispositivos ativos",
  profileSecurityPanelDescription: "Encerre acessos que você não reconhece.",
  profileSecurityRevokeOthers: "Encerrar todas as outras",
  profileSecuritySessionCurrent: "Sessão atual",
  profileSecuritySessionExpiresPrefix: "Expira em",
  profileSecuritySessionNoIp: "IP não identificado",
  profileSecuritySessionNoActivity: "Sem atividade",
  profileSecuritySessionClose: "Encerrar",
  profileSecuritySessionUpdated: "Sessões atualizadas com sucesso.",

  profilePrivacyTitle: "Privacidade",
  profilePrivacyDescription: "Exporte seus dados e solicite exclusão da conta.",
  profilePrivacyLoading: "Carregando privacidade...",
  profilePrivacyExportTitle: "Exportar meus dados",
  profilePrivacyExportDescription: "Gere um pedido para receber seus dados em JSON.",
  profilePrivacyExportRequest: "Solicitar exportação",
  profilePrivacyExportRequesting: "Solicitando...",
  profilePrivacyExportCreatedPrefix: "Solicitação de exportação criada:",
  profilePrivacyDeleteTitle: "Solicitar exclusão da conta",
  profilePrivacyDeleteDescription: "Seu pedido será analisado antes da confirmação final.",
  profilePrivacyDeleteReason: "Motivo (opcional)",
  profilePrivacyDeleteReasonPlaceholder: "Motivo da solicitação",
  profilePrivacyDeleteConfirmLabel: "Digite EXCLUIR MINHA CONTA para confirmar",
  profilePrivacyDeleteConfirmPlaceholder: "EXCLUIR MINHA CONTA",
  profilePrivacyDeleteSubmit: "Solicitar exclusão",
  profilePrivacyDeleteSubmitting: "Enviando...",
  profilePrivacyDeleteCreatedPrefix: "Solicitação de exclusão criada:",
  profilePrivacyExportError: "Não foi possível solicitar exportação.",
  profilePrivacyDeleteError: "Não foi possível solicitar exclusão.",
} as const;

export type CopyKey = keyof typeof copyCatalog;

export const copy = (key: CopyKey): string => copyCatalog[key];

export const copyList = (...keys: CopyKey[]): string[] => keys.map((key) => copy(key));

export const formatCityNowShowingLabel = (state: string) => `${state} • ${copy("headerNowShowingToday")}`;

export const formatSearchDesktopPlaceholder = (cityLabel: string) =>
  `${copy("searchDesktopPlaceholderPrefix")} ${cityLabel}`;

export const formatSearchMobilePlaceholder = (cityLabel: string) =>
  `${copy("searchMobilePlaceholderPrefix")} ${cityLabel}`;

export const formatReleaseDateLabel = (date: string) => `Estreia ${date}`;

export const formatNextSessionLabel = (label: string) => `${copy("movieCardNextSessionPrefix")} ${label}`;

export const formatSessionsCountLabel = (count: number) =>
  `${count} ${copy("movieCardSessionsSuffix")}`;

export const formatCurrencyFromLabel = (value: string) => `${copy("movieCardPriceFromPrefix")} ${value}`;

export const formatProfileOverviewTitle = (firstName: string) =>
  `${copy("profileOverviewTitlePrefix")}${firstName || "cliente"}`;

export const formatProfileActiveSessionsLabel = (count: number) =>
  `${copy("profileOverviewActionSessions")} (${count})`;
