import {
  Apple,
  ArrowRight,
  ArrowUpRight,
  Building2,
  Calendar,
  ChevronDown,
  CircleAlert,
  Clock3,
  CreditCard,
  Download,
  Film,
  Info,
  LoaderCircle,
  Mail,
  MapPin,
  MoonStar,
  Play,
  Popcorn,
  QrCode,
  Search,
  Sparkles,
  SunMedium,
  Smartphone,
  Ticket,
  TimerReset,
  User,
  WalletCards,
  X,
  ZoomIn,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconRegistry = {
  apple: Apple,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  building: Building2,
  calendar: Calendar,
  chevronDown: ChevronDown,
  clock: Clock3,
  creditCard: CreditCard,
  download: Download,
  email: Mail,
  error: CircleAlert,
  film: Film,
  info: Info,
  loader: LoaderCircle,
  mapPin: MapPin,
  moon: MoonStar,
  play: Play,
  popcorn: Popcorn,
  qrCode: QrCode,
  search: Search,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sun: SunMedium,
  ticket: Ticket,
  timer: TimerReset,
  user: User,
  wallet: WalletCards,
  x: X,
  zoomIn: ZoomIn,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
